version: '3.5'
services:
  logview:
    image: logview
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/
    ports:
    - 8080:8080
    volumes:
      - "/etc/group:/etc/group:ro"
      - "/etc/passwd:/etc/passwd:ro"
#      - "/var/logs/:/app/mnt/logs/"
